export const ADD_SONGS = "ADD_SONGS"
export const REMOVE_SONGS = "REMOVE_SONGS"
export const TOGGLE_PLAYING = "TOGGLE_PLAYING"
export const FILTER_SONGS = "FILTER_SONGS"
export const PLAY_SONG = "PLAY_SONG"
export const SHUFFLE = "SHUFFLE"
export const SET_SHUFFLE = "SET_SHUFFLE"
export const REPEAT = "REPEAT"
